

=== ((Asana)) ((Yoga))

Ecco un elenco delle (((posizioni yoga))) più comuni. Sono riassunte con il seguente modello:

.modello asana
((nome)):: 
    image:figures/empty_3cmx5cm.svg[role=right]
    _Sinomimi_: ((posizione del ................)), + 
    ((posizione del .........)). +
    _Respiro_: inspirare / espirare / apnea. Da considerare se eseguito in una sequenza. Per posizione mantenuta non considerare. +
    _Esecuzione_: Istruzioni per l'esecuzione. Eventuali riferimenti. +
    _Effetti_: Effetti dell'asana.


((adho mukha svanasana))::
    image:figures/asana_yoga/adho_mukha_svanasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((cane a faccia in giù)), ((downward-facing dog)) +
    _Esecuzione_: Portando il peso sulle braccia, estendere le gambe alzando il bacino. Mantenere le piante dei piedi ben a terra. Inserire la testa tra le braccia, formando un triangolo con la schiena e le gambe ben dritte. +
    _Effetti_: La posizione ha lo scopo di allungare la schiena e fortificare le braccia e le gambe. +

((ashtanga namaskara))::
    image:figures/asana_yoga/ashtanga_namaskara.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((Saluto con gli “otto” arti del corpo)) +
    _Respiro_: espirare +
    _Esecuzione_: espirare portando a terra le ginocchia, il petto e la fronte, tenendo sollevati il bacino e lo stomaco. +
    _Effetti_: buonissimi.
   
((ashwa sanchalanasana))::
    image:figures/asana_yoga/ashwa_sanchalanasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: _((posizione equestre))_ +
    _Respiro_: inspirare +
    _Esecuzione_: estendendere la gamba sinistra indietro; contemporaneamente piegare il ginocchio destro e guardare in alto sollevando il mento. +
    _Effetti_: buonissimi.

((baddha konasana))::
    image:figures/asana_yoga/baddha_konasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione della farvalla)) +
    _Esecuzione_: Eseguire la posizione della farfalla +
    _Effetti_: buonissimi.

((bhujangasana)):: 
    image:figures/asana_yoga/bhujangasana.svg[role=right, pdfwidth=5cm]
    _Sinomimi_: ((posizione del cobra)), ((posizione del serpente)). +
    _Respiro_: inspirare +
    _Esecuzione_: Partendo dalla posizione prona, con il corpo disteso sulla pancia e le gambe unite e parallele con le cosce al suolo e piedi distesi e allungati sul dorso, si piegano le braccia portando i palmi delle mani a terra all'altezza delle spalle. Inspirando, si solleva il busto con le braccia, distendendole, mantenendo cosce e pube a contatto con il suolo. Sguardo in alto. +
    _Effetti_: rinforza i muscoli dorsali, promuove la flessibilità della colonna vertebrale e stimola la circolazione sanguigna nella regione spinale tonificando i plessi nervosi. Gli effetti di questo âsana interessano tutte le vertebre: una pratica attenta e costante permette la correzione di eventuali deviazioni della colonna vertebrale. Bhujangâsana risulta particolarmente efficace nell'affrontare dolori e irregolarità mestruali, costipazione e lombaggine. Vengono stimolati tutti gli organi addominali, in modo particolare il fegato e i reni. E' considerato un ottimo esercizio per la preparazione al parto, anche se non deve essere eseguito durante il periodo della gravidanza. footnote:[Fonte: http://www.yoga.it/articoli/bhujangasana-il-cobra/]
    
((halasana))::
    image:figures/asana_yoga/halasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione dell' aratro)) +
    _Esecuzione_: Eseguire la posizione dell'aratro  +
    _Effetti_: buonissimi.

((hasta uttanasana))::
    image:figures/asana_yoga/hasta_uttanasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione delle mani sollevate)) +
    _Esecuzione_: Inspirare distendendo le braccia verso l’alto e flettendo il tronco all’indietro. +
    _Effetti_: buonissimi.

((karnapidasana))::
    image:figures/asana_yoga/karnapidasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione dell'aratro modificato)) +
    _Esecuzione_: posizione dell'aratro modificato +
    _Effetti_: buonissimi.

((janu sirsasana))::
    image:figures/asana_yoga/janu_sirsasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione piegata sulla gamba destra o sinistra)) +
    _Esecuzione_: posizione piegata sulla gamba destra o sinistra  +
    _Effetti_: buonissimi.

((supta baddha konasana))::
    image:figures/asana_yoga/supta_baddha_konasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione del calzolaio)) +
    _Esecuzione_: Eseguire la posizione del calzolaio  +
    _Effetti_: buonissimi.

((padahastasana))::
    image:figures/asana_yoga/padahastasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: _((posizione delle mani ai piedi))_ + 
    _Esecuzione_: espirare piegandosi in avanti partendo dai fianchi, fino ad appoggiare i palmi delle mani a terra ai lati dei piedi. +
    _Effetti_: buonissimi.
   
((paschimottanasana))::
    image:figures/asana_yoga/paschimottanasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione seduta in avanti)) +
    _Esecuzione_: Eseguire la posizione seduta in avanti  +
    _Effetti_: buonissimi.

((pranamasana))::
    image:figures/asana_yoga/pranamasana.svg[role=right]
    _Sinonimi_: ((posizione della preghiera)) +
    _Esecuzione_: Espirare con i piedi uniti e le mani giunte davanti al petto.  
    _Effetti_: buonissimi.

((sarvangasana))::
    image:figures/asana_yoga/sarvangasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione della candela)) +
    _Esecuzione_: Eseguire la posizione della candela +
    _Effetti_: buonissimi.

((shashankasana))::
    image:figures/asana_yoga/shashankasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione della lepre)) +
    _Esecuzione_: Eseguire la posizione della lepre +
    _Effetti_: buonissimi.

((shavasana))::
    image:figures/asana_yoga/shavasana.svg[role=right]
    _Sinonimi_: ((posizione del cadavere)), ((Mrtasana)), ((savasana)) +
    _Esecuzione_: Savasana è una posizione di rilassamento totale, quindi anche una delle asana più impegnative. +
    _Effetti_: buonissimi.
    
((upavishta konasana))::
    image:figures/asana_yoga/upavishta_konasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((seduta ad angolo)) +
    _Esecuzione_: Eseguire la seduta ad angolo +
    _Effetti_: buonissimi.
     
((uttanasana)) footnoteref:[uttanasana, https://it.wikipedia.org/wiki/Uttanasana] ::
    image:figures/asana_yoga/uttanasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione della pinza in piedi)) +
    _Esecuzione_: Partendo dalla posizione in piedi, con la schiena dritta ed i piedi distanti come l'apertura delle anche e le braccia allungate oltre la testa, espirando si piega il bacino muovendo il corpo come fosse formato da due tronconi, allungando le mani fino a raggiungere le caviglie, il dorso dei piedi o sotto la pianta dei piedi, appoggiando il tronco parallelo alle gambe. +
    _Effetti_: La posizione ha lo scopo di allungare la schiena, traendola in senso conforme dell'usuale incurvatura. Crea benefici alla colonna vertebrale, distendendola footnoteref:[uttanasana].
    
     
((utthita sarvangasana))::
    image:figures/asana_yoga/utthita_sarvangasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione della candela aiutata destra o sinistra)) +
    _Esecuzione_: Eseguire la posizione della posizione della candela aiutata destra o sinistra +
    _Effetti_: buonissimi.


((vajrasana)) footnote:[https://it.wikipedia.org/wiki/Vajrasana]::
    image:figures/asana_yoga/vajrasana.svg[role=right, pdfwidth=5cm]
    _Sinonimi_: ((posizione del diamante)), ((posizione del tuono)) +
    _Esecuzione_: Inginocchiarsi a terra sedendosi sui piedi, appoggiati con il dorso a terra, e mantenendo la spina dritta e verticale con il collo allineato con essa. Le mani saranno appoggiate sulle ginocchia. I piedi possono rimanere paralleli e appoggiati a terra sul dorso. +
    _Effetti_: La posizione ha lo scopo preparare alla meditazione.



=== Sequenze Yoga

.Rilassamento footnote:[vajrasana 120, shashankasana 180, adho_mukha_svanasana 60, uttanasana 120, baddha_konasana 60, upavishta_konasana 120, janu_sirsasana 60x2, paschimottanasana 240, shavasana 60, halasana 30, sarvangasana 60, utthita_sarvangasana 60x2, karnapidasana 30, halasana 30, shavasana 30, supta_baddha_konasana 300, shavasana 300]
[header=yes, cols="^1,2,1"]
|===
| Posizione | Descrizione | Secondi
| image:figures/asana_yoga/vajrasana.svg[role=right, pdfwidth=5cm] | Inginocchiarsi a terra sedendosi sui piedi, appoggiati con il dorso a terra, e mantenendo la spina dritta e verticale con il collo allineato con essa. Le mani saranno appoggiate sulle ginocchia. I piedi possono rimanere paralleli e appoggiati a terra sul dorso. | 120 
| image:figures/asana_yoga/shashankasana.svg[role=right, pdfwidth=5cm] | Eseguire la posizione della lepre | 180 
| image:figures/asana_yoga/adho_mukha_svanasana.svg[role=right, pdfwidth=5cm] | Portando il peso sulle braccia, estendere le gambe alzando il bacino. Mantenere le piante dei piedi ben a terra. Inserire la testa tra le braccia, formando un triangolo con la schiena e le gambe ben dritte. | 60 
| image:figures/asana_yoga/uttanasana.svg[role=right, pdfwidth=5cm] | Inspirare distendendo le braccia verso l’alto e flettendo il tronco all’indietro. | 120 
| image:figures/asana_yoga/baddha_konasana.svg[role=right, pdfwidth=5cm] | Eseguire la posizione della farfalla | 60 
| image:figures/asana_yoga/upavishta_konasana.svg[role=right, pdfwidth=5cm] | Eseguire la seduta ad angolo | 120 
| image:figures/asana_yoga/janu_sirsasana.svg[role=right, pdfwidth=5cm] | posizione piegata sulla gamba destra o sinistra  | 60 
| image:figures/asana_yoga/janu_sirsasana.svg[role=right, pdfwidth=5cm] | altro lato | 60 
| image:figures/asana_yoga/paschimottanasana.svg[role=right, pdfwidth=5cm] | Eseguire la posizione seduta in avanti  | 240 
| image:figures/asana_yoga/shavasana.svg[role=right, pdfwidth=5cm] | Savasana è una posizione di rilassamento totale, quindi anche una delle asana più impegnative. | 60 
| image:figures/asana_yoga/halasana.svg[role=right, pdfwidth=5cm] | Eseguire la posizione dell'aratro  | 30 
| image:figures/asana_yoga/sarvangasana.svg[role=right, pdfwidth=5cm] | Eseguire la posizione della candela | 60 
| image:figures/asana_yoga/utthita_sarvangasana.svg[role=right, pdfwidth=5cm] | Eseguire la posizione della posizione della candela aiutata destra o sinistra | 60 
| image:figures/asana_yoga/utthita_sarvangasana.svg[role=right, pdfwidth=5cm] | altro lato | 60 
| image:figures/asana_yoga/karnapidasana.svg[role=right, pdfwidth=5cm] | posizione dell'aratro modificato | 30 
| image:figures/asana_yoga/halasana.svg[role=right, pdfwidth=5cm] | Eseguire la posizione dell'aratro  | 30 
| image:figures/asana_yoga/shavasana.svg[role=right, pdfwidth=5cm] | Savasana è una posizione di rilassamento totale, quindi anche una delle asana più impegnative. | 30 
| image:figures/asana_yoga/supta_baddha_konasana.svg[role=right, pdfwidth=5cm] | Eseguire la posizione del calzolaio  | 300 
| image:figures/asana_yoga/shavasana.svg[role=right, pdfwidth=5cm] | Savasana è una posizione di rilassamento totale, quindi anche una delle asana più impegnative. | 300 
|===

https://youtu.be/F06yrI5Hxl4


.Saluto al sole
[header=yes, cols="^1,2"]
|===
| image:figures/asana_yoga/pranamasana.svg[] | posizione della preghiera: ((Pranamasana)) espirare con i piedi uniti e le mani giunte davanti al petto.
| image:figures/asana_yoga/hasta_uttanasana.svg[] | posizione delle mani sollevate: ((Hasta uttanasana)) inspirare distendendo le braccia verso l’alto e flettendo il tronco all’indietro.
| image:figures/asana_yoga/padahastasana.svg[] | posizione delle mani ai piedi: (Padahastasana) espirare piegandosi in avanti partendo dai fianchi, fino ad appoggiare i palmi delle mani a terra ai lati dei piedi.
| image:figures/asana_yoga/ashwa_sanchalanasana.svg[scaledwidth=50%] | posizione equestre: (Ashwa sanchalanasana) Inspirare stendendo la gamba sinistra indietro; contemporaneamente piegare il ginocchio destro e guardare in alto sollevando il mento.
| image:figures/asana_yoga/adho_mukha_svanasana.svg[] | posizione del cane che guarda indietro: (Adho mukha svanasana) trattenere il respiro e portare il piede destro indietro, vicino al sinistro. Obiettivo è che il corpo formi una linea dritta.
| image:figures/asana_yoga/ashtanga_namaskara.svg[] | Saluto con gli “otto” arti del corpo: (Ashtanga namaskara) espirare portando a terra le ginocchia, il petto e la fronte, tenendo sollevati il bacino e lo stomaco.
| image:figures/asana_yoga/bhujangasana.svg[] | posizione del serpente (o del cobra): ((Bhujangasana)) inspirare e guardare in alto, sollevando la parte superiore del corpo e le braccia.
| image:figures/asana_yoga/adho_mukha_svanasana.svg[] | posizione del cane che guarda indietro: (Adho mukha svanasana) espirare con le mani a terra, portando la punta dei piedi in avanti e spingendo le natiche verso l’alto e all’indietro.
| image:figures/asana_yoga/ashwa_sanchalanasana.svg[] | posizione equestre: (Ashwa sanchalanasana) inspirare portando il piede sinistro tra le mani. Vi troverete con la gamba destra tesa all’indietro e il ginocchio poggiato a terra.
| image:figures/asana_yoga/padahastasana.svg[] | posizione delle mani ai piedi: (Padahastasana) espirare portando la gamba destra vicino alla sinistra e il bacino verso l’alto. Avvicinate il viso alle gambe.
| image:figures/asana_yoga/hasta_uttanasana.svg[] | posizione delle mani sollevate: (Hasta uttanasana) distendete le braccia in avanti, poi verso l’alto e oltre la testa, piegandovi all’indietro con le mani unite.
| image:figures/asana_yoga/pranamasana.svg[] | posizione della preghiera: (Pranamasana) chiudere il ciclo con la posizione numero 1.
|===



