
== Musica


=== Teoria

==== 4 accordi POP

G, D, Em, C
I V vi IV

.((Progressione I I7 IV V7))
[format="csv", options="header"]
|===
I, ii, iii, IV, V, vi, vii
C, D, E, F, G, A, B
F, G, A, Bb, C, D, E
G, A, B, C, D, E, F#
A, B, C#, D, E, F#, G#
D, E, F#, G, A, B, C#
|===


=== ((Ukulele))
Accordi ukulele – Maggiori

[options="header", cols="3,1,1,1"]
|========= 
| Nota | 1 | 2 | 3 
| C (Do) | 0·0·0·3 | 0·4·0·3 | 0·7·8·7 | 
D (Re) | 2·2·2·0 | 2·2·2·5 | 7·6·5·0 |
E (Mi) | 4·4·4·2 |  4·4·0·2 | 4·4·4·7 | 
F (Fa) | 2·0·1·0 |  5·5·5·0 | 5·5·5·8 | 
G (Sol) | 0·2·3·2 |  0·2·3·5 | 0·7·7·5 | 
A (La) | 2·1·0·0 |  6·4·5·0 (Peppa Pig) | 2·4·0·4 | 
B (Si) |  4·3·2·2 | 4·3·2·6 | 8·6·7·9 | 
Cm (Do minore) | 0·3·3·3 | 0·7·8·6 | 0·0·11·12 | 
Dm (Re minore) | 2·2·1·0 | 7·5·5·0 | 9·9·8·7 | 
Em (Mi minore) | 0·4·0·2 | 4·4·3·2 | 0·7·7·7 | 
Fm (Fa minore) | 1·0·1·3 | 5·5·4·3 | 5·5·8·8 | 
Gm (Sol minore) | 0·2·3·1 | 0·7·6·5 | 0·7·6·10 |
Am (La minore) | 2·0·0·0 | 2·4·5·0 (Powerchord) | 7·9·8·7 | 
Bm (Si minore) | 4·2·2·2 | 4·6·7·5 | 7·6·7·5 | 
C7 (Do7) | 0·0·0·1 |  | | 
D7 (Re7) | 2·2·2·3 |  | |
E7 (Mi7) | 4·4·4·2 |  | | 
F7 (Fa7) | 2·0·1·0 |  | | 
G7 (Sol7) | 0·2·3·2 | | | 
A7 (La7) | 2·1·0·0 |  | | 
B7 (Si7) |  4·3·2·2 | | | 
|========= 

==== Esercizi Strumming

.Nomenclatura
|====
| u | up, mezza battuta  | d | down, mezza battuta 
| U | up, una battuta | D | down, una battuta 
| u+ | up, 3/4 di battuta  | d+ | down, 3/4 di battuta  
| u- | up, 1/4 di battuta  | d- | down, 1/4 di battuta 
| . | 1/2 di battuta senza gesti | |
|====


.4/4
|====
| basic | D | D | D | D
| standard | u d | u d | u d | u d
| swing | u+ d- | u+ d-| u+ d-| u+ d-
| church | D | d U | D | d U 
| calipso | d . | d u | . u | d .
| standard | u | u d | u | ud
|====

.3/4
|====
| u | u d | ud
|====

==== Arpeggi

.Nomenclatura
|====
| p1 | pollice corda 1 footnote:[la prima a sx nelle tablature]
| p2 | pollice corda 2
| 13 | indice corda 3
| 24 | indice corda 4
|====

.Arpeggi
|====
| base  | 1 2 3 4
| alternato | 1 3 2 4
| mike1 | 1 3 4 3 - 2 3 4 3
| scarlborough | 1 2 3 4 3 2 
|====

=== Songs

((a children's lullaby)) footnote:[https://youtu.be/XyfPJ6JNlfU?list=PLR-lgQYwrszE55v7gWoYm-FsWH5Mps4xW]:: Progressione I V7, Tonalità C +
4/4 Pattern C G7 C G7

((amazing grace)) footnote:[https://youtu.be/Zj-xa9sLNyY?list=PLR-lgQYwrszE55v7gWoYm-FsWH5Mps4xW]:: Progressione I I7 IV V7, Tonalità C +
4/4 pattern C C7 F C/C7 | F C C G7/C

((banana boat song)):: Progressione I, V7, I rit I IV I +
Tonalità C + 
4/4 calypso C G7 C, C F C +

((Blues improvvisation)):: Progressione I, IV, V +
Tonalità D7 + 
4/4 pattern D7x16 G7x8 D7x8 A7x4 G7x4 +
Per assolo: -, 2 5, 3 5, 3 5

((Fra' Martino)):: *Note* C 

((London Bridge)):: Progressione I V7, Tonalità C +
4/4 pattern C C G7 C

((yellow submarine)):: Progressione I7 III VI I7, Tonalità G7 +
4/4 pattern 4X (G7  C F G7) 2X (C G7 G7 C)

((You're my sunshine)):: Progressione I, I7, IV rit I V7 I +
4/4 swing C C7 F C rit. C G7 C

((over the rainbow)):: Progressione I IIIm IV I IV III7 VIm IV, Tonalità C +
4/4 pattern 4X (C Em F C F E7 Am/F) 2X (C G Am F)


((Se sei felice e tu lo sai))footnote:[https://youtu.be/elTDFX9r_9k?list=PLR-lgQYwrszE55v7gWoYm-FsWH5Mps4xW]:: 4/4 pattern:  G D7 D7 G | C G D7 G

((The lion sleeps tonight)):: Progressione I IV I V, Tonalità G
4/4 pattern G C G D


.Risorse utili da cui ho tratto le info di questo capitolo
* https://www.youtube.com/user/MusicTeacher2010/
* 
