

== Comunicazione 

=== Checklists

((Avoid Meetings)):: usa almeno 3 volte una di queste tecniche ((evitare riunioni))

	** Make it known that the company would be better served if you weren’t there.
	** Be candid, honest, and authentic while you explain. Lying might work, but it will come back to bite you.
	** Provide more information than the person needs to know.
	** Talk to whoever is in charge and get their blessing to bail.
	
((Scoprire un bugiardo)):: Osserva il modo con cui la persona dice no: footnote:[http://lifehacker.com/spot-a-liar-by-listening-to-how-they-say-no-1732665074]
	
	** say “no” and look in a different direction;
	** say “no” and close their eyes;
	** say “no” after hesitating;
	** say “noooooooo,” stretched over a long period of time;
	** say “no” in a singsong manner.

== Everiday thinking

6 passaggi per cambiare opinione:

. what do you really believe anyway?
. how well based is the opinion that you already hold?
. how good is the evidence? Is it based on experiments?
Is it based on that personal experience? How good are the data? How good is that evidence?
. does the evidence really
contradict what you already believe?
.  if that's not enough,
what would be enough?
. is it worth finding out
about, or is just a case of why not? Why don't I just continue to believe this stuff? What's
the cost? Can I just persist in this belief?


Tim Minchin has a really nice example of this.
"The Fence"

=== Problemi cognitivi footnoteref:[wikipedia, https://en.wikipedia.org]

. *((anchoring))*,  tendency to rely too heavily on the first piece of information offered (the "anchor") when making decisions.
. *((False Consensus))*, a person tends to overestimate the extent to which their beliefs or opinions are typical of those of others.
. *((A Channel Factor))*, Channel factors are small but critical factors that facilitate or create barriers for behavior.
. *((The Fundamental Attribution Error))*, The tendency for people to over-emphasize personality-based explanations for behaviors observed in others while under-emphasizing the role and power of situational influences on the same behavior
. *((The Fundamental Cognitive Error))*,  People tend to underestimate the contribution of their beliefs & theories to observation & judgement 
. *((Cognitive Dissonance))*,  mental stress or discomfort experienced by an individual who holds two or more contradictory beliefs, ideas, or values at the same time, performs an action that is contradictory to one or more beliefs, ideas or values, or is confronted by new information that conflicts with existing beliefs, ideas, or values. 
. *((Hindsight bias))*, after an event has occurred, to see the event as having been predictable, despite there having been little or no objective basis for predicting it.
. *((Illusory correlation))*, is the phenomenon of perceiving a relationship between variables (typically people, events, or behaviors) even when no such relationship exists.

.((flashcards problemi cognitivi))
[format="csv", cols="^1,1", options="header"]
|===
*Concetto*, *definizione*
include::flashcards/problemi_cognitivi.txt[]
|===

.((flashcards HIP))
[format="csv", cols="^1,1", options="header"]
|===
*Concetto*, *definizione*
include::flashcards/hip.txt[]
|===


== Negoziazione


.Saluta!
if negotiators get a chance to communicate with each other, just a few minutes of describing
their interests or values, they do better in negotiations and they’ll be more
likely to cooperate in the prisoners dilemma game, 

.Keith Spicer
Selezione:: la nostra mente è un magazzino finito, non può trattenere tutto e deve selezionare necessariamente. Se non vogliamo che questa selezione sia fatta dai nostri interlocutori con il rischio che selezionino ciò che vogliono loro e non ciò che vogliamo noi, è necessario che si operi questo filtro fin dall'inizio. 

Sintesi:: conseguenza della selezione. Grazie alla capacità di analisi, dobbiamo poi rispettare la risorsa più preziosa che noi e gli altri abbiamo  e di cui lamentiamo sempre la mancanza: il tempo.  Arrivare al punto, focalizzare la nostra e altrui attenzione su poche cose, ma quelle importanti, è il modo per gestire al meglio il tempo e soprattutto i meccanismi della nostra mente, che non ci consentono di superare una certa soglia di attenzione.

Struttura:: quanto sopra non è praticabile in assenza di una struttura, di un metodo e di una razionalizzazione dei nostri flussi comunicazionali. E contrariamente a quanto spesso si pensa è proprio un metodo che dà libertà, perché una volta che se ne dispone si può liberamente da libero sfogo ai suggerimenti che ci offrono istinto, talento e esperienza.

.In caso di Maleducazione footnote:[Gavin Kennedy, *'Everything Is Negotiable'*, Random House Business Books, 1997 (3rd Edition).]: "il Vostro comportamento non modificherà la riuscita della negoziazione"

.Gavin Kennedy

The following article is an extract from
[www.stellarleadership.com](www.stellarleadership.com) and talks about
Mr Kennedy books footnote:[Gavin Kennedy, *'Everything Is Negotiable'*, Random House Business Books, 1997 (3rd Edition).].

Kennedy believes that in order to learn about negotiation effectively,
the process should be enjoyable, and to that end, he uses
classifications for negotiators:

-   *Sheep*: easily led into choices by other people. Accepts situations
    at face value, preferring to submit rather than
    defend self-interests.
-   *Donkeys*: react in a ‘knee-jerk’ manner, often stubborn, sticking
    to deeply held principles through ignorance.
-   *Foxes*: succeed through knowing the situation, and cunning. Experts
    at exploiting sheep and donkeys, but risk being too clever for their
    own good.
-   *Owls*: are sensitive to longer-term benefits of developing
    relationships through negotiating to get well-deserved results. They
    earn the respect of others, and are well prepared for threats and
    seizing opportunities.

Rules for a good negotiation:

1.  Never accept the first offer
2.  If a grievance exists, don’t just complain, negotiate a solution
3.  Never improve an offer without having received a counter-offer
4.  Always ask “what if?” when presented with an offer, until all
    eventualities are covered
5.  Never concede anything to gain goodwill, or to get the ball rolling
6.  Make the opening offer as low/high as possible, without becoming
    laughable
7.  Make decisions concerning the potential boundaries of the deal, and
    stick to them in the negotiation. Don’t let that resolve weaken
8.  Don’t be afraid to say no to an offer or a deal, but come back with
    "if..."
9.  Find out who is really doing the buying/selling
10. Don’t look solely at the price, consider the whole package:
    delivery, cost of production, quality etc
11. Don’t be fooled by superficial appearances, they are meaningless
12. Avoid making threats in a negotiation; they are almost always
    counter-productive



== Vendita

=== SPIN Selling

SPIN  è un acronimo e individua 4 diversi tipi di domande:

Situation Questions:: fatte per acquisire fatti. "Quanti dipendenti avete?". Sono tipiche dei venditori meno efficaci.
Problem Questions:: poste per fare emergere problemi. "Quali inconvenienti vi trovate a affrontare con questa macchina?". Sono formulate da chi ha maturato un approccio consulenziale e relazionale alla vendita.
Implication Questions:: poste per fare emergere le implicazioni e le conseguenze negative di un eventuale problema, insoddisfazione o disaffezione. "Il problema così come me lo ha esposto che conseguenze ha?". Tipiche di chi, da vero consulente, non ha "visioni sue" precostituite.
Need pay off Questions:: aiutano a percepire il valore della nostra soluzione. "Quanto risparmiereste se aveste una macchina con queste caratteristiche...?". Sono poste per fare acquisire al cliente la consapevolezza che la  soluzione che il venditore offre è vantaggiosa economicamente.


