
== Public Speaking

=== Suggestion

Please with threes::footnoteref:[littime, http://www.wikihow.com/Give-a-Powerful-Presentation-when-You-Have-Little-Time-to-Prepare]  Otherwise called the "rule of threes", this means that you create a presentation using a speech structure that consists of three main components: an opening, a body, and a closing. Manage these three major parts of a presentation and your speech will be organized every time.

Grab your listeners’ attention right away by beginning with the issue about which you are asked to speak:: footnoteref:[littime] You can do this by asking a question that directly reflects back to the topic. For example, if you are asked to present the status of a project, begin your presentation with the question, “One of our current projects is Project You-Name-It. Just where do we currently stand at this point with Project You-Name-It, and are we on track for our end goal?” Miracle of miracles! This is exactly what everyone in the room is there to find out so you immediately have their attention. You also buy yourself a few more seconds to figure out what you need to tell them.

Keep it going:: footnoteref:[littime] The body of your presentation – whether it takes five minutes or fifty minutes to present – should then answer the question posed in your opening. You have valuable information to give to the attendees and you have their attention.

Plan to cover no more than three points in the body of your presentation:: footnoteref:[littime] People best retain up to three pieces of information so list those three project points to the group up front. 

Tell them in broader detail what you just outlined:: footnoteref:[littime] If you are up-to-date with your project, you should already know this information and can expand upon it. The last statement in the body of your speech should then summarize the three points you just explained. You could say, “In summary, where things stand include Points One, Two, and Three. And we will overcome these concerns and move the project forward by doing actions a, b, and c”.

Bring it to a close:: footnoteref:[littime] The final part of the three-part presentation structure is a summary and closing statement. Start a powerful closing statement by addressing the opening question. This brings the presentation full circle and sums up why everyone is listening. Then ask whether you answered all concerns, and field questions. Finish your presentation by calling the group to action or reaffirming everyone’s commitment to the project. Examples might include, “With the status I just presented, I ask that you continue your commitment to move forward with the project,” or “With the concerns I addressed, I ask that you designate another person to help with the task at hand.” These steps reaffirm the commitment of the group members or of management.



=== A guide to impromptu speaking


ATM-S Chris Ng Wai Chung teaches you how to survive the fear and trauma of speaking unprepared when you are made to do impromptu speaking in front of an audience. footnote:[http://www.expressyourselftosuccess.com/how-to-organize-an-impromptu-speech/]

[quote, Emiliano Zapata, Mexican Revolutionary]
“It is better to die on your feet than to live on your knees.”

About 18 years ago, I was asked by my primary school principal to step onto the stage to explain to about a thousand fellow primary school students why I did not pay my milk-money. Without hesitation, I proceeded to wet my pants. That feeling of deja vu repeated itself when I was 17 in junior college. After applying for the Plain English Speaking Competition, I surprised myself during the auditions for having only said about 5 sentences to a group of stunned teacher-panelists after I was given my first table topic. ( After which I ran out of the classroom ). While the above scenario may seem familiar to many of you, I’ve seen many dramatic turnarounds from the public speaking disasters in my past. Diane was this lady who was my schoolmate in NJC , after her round of auditions, I remember her telling the group of us hopefuls that she really screwed up and was too nervous to perform, she eventually became the best speaker in the JC debates in 1992 with her name appearing in the newspapers after her hard earned victory. And some of us have heard of the “Scat-man” song on the radio ( truth is, he stutters ).
This article hopes to dispel the myths of impromptu speaking and highlights the PREP formula as taught by the Toastmaster’s movement. It will then give some tips on how to build your repertoire of speeches to make it truly memorable.

==== Impromptu Speaking Basics : PREP formula

There are many strategies which public speakers employ to create the illusion of confidence on stage. Fact of the matter is that most public speakers have butterflies in their stomachs. The trick is to make them fly in formation. The Toastmasters movement suggests the use of the PREP formula and it goes like this :

P :: Point—State your point to the question.
R :: Reason—State a reason why you raised your point.
E :: Example—Give an illustration which supports your above-mentioned case.
P :: Prep—Which leads us to the next point.

By employing this strategy, you “daisy-chain” your response to the table topics and could speak endlessly about the topic given to you.
.Example 
Topic :: Is Batman is more intelligent than Superman ? Elaborate on your answer.
Point :: I believe with great conviction that there is incontrovertible evidence that Batman, the caped crusader demonstrates a much greater intellect than Superman, the Man of steel.
Reason :: One of the reasons is that Batman, having no supernatural powers, relies solely on his wits and technology whereas Superman is blessed with the powers of flight and superhuman strength.
Example :: In the latest confrontation with the Joker, Batman outsmarted the Joker by causing the Joker to slip on a banana peel and fall into gigantic toilet bowl. The latest comic shows Superman beheading Lex Luthor with a casual flick of his index finger and sending his head into planetary orbit.
Point :: Which brings us to the question of Superman’s brutality that which could only be found in basest of primates.

==== For Intermediate speakers : Speech frameworks

The PREP technique is all it takes to survive a gruesome one to two minute table topics session, but for longer speeches, the constant use of this framework, could put the most attentive speakers to sleep. Intermediate speakers consider the following frameworks which could be constructed to supplement their speeches. If the speaker’s level of proficiency were a pimple it’d turn dark and purple at this stage.
Three of the most commonly observed frameworks are highlighted here.

.Basic framework
This style begins by an introduction to the subject matter, a definition to the problem and plenty of sign postings which guide the listener to the actual body of the speech. The body of the speech contains about 2 to 3 PREP cycles which reinforces the point the speaker wishes to make. And the speaker concludes the speech by a call to action or reaffirms his stand on the subject matter. The speaker would usually employ the phrases “First of all”, “Secondly” and “Finally” to break his speech down into logical components.

.Pros/Cons Framework
This framework considers a yes/no problem like “Should abortion be banned in Singapore”.The speaker then proceeds to use the “On one hand…”and the “On the other hand…” in the speech body to consider both sides of the coin, then the speaker concludes by taking a stand and giving the reasons why one case is stronger than the other.
Caution : Practiced wrongly, the speaker will seem to be indecisive at a taking a stand so be sure to make one case weaker than the other.

.Chronological
This framework applies to questions where historical examples be used to reinforce the points the speaker has to make. Questions like “Is the feminist movement still relevant in modern society today?” The speaker could begin the body of the speech by using the words “In the past,,,” and then subsequently use the words “Now times have changed…” and even take the opportunity to contemplate the future by considering “Perhaps in the near future we would be able to…”


==== Advanced speakers : Unique Selling Propositions

The greatest speakers have something special which distinguishes them from other speakers in that they are unique and offer something to the listener be it hope, joy or enlightenment. At this point, you should think of Marilyn Monroe who has that pout which made her a legend or Jennifer Lopez’s….errrrmmm….beautiful face.
Here are the possible things advanced speakers do to make their speech truly memorable.

The Flirt:: Charm the audiences by enforcing a personal stake in the presentation.
  Many impromptu speakers flirt with the audience and end up with most of the awards when the event is over. This technique keeps the audience riveted by picking on someone from the audience – this creates a personal atmosphere. Occasionally, if a roast becomes inappropriate when used on someone else, the speaker would often employ himself/herself as subject matter.
  A Microsoft salesman in a technical conference had probably made arrangements with a fellow employee to seek permission to use him in a speech delivery would begin by saying “Suppose our friend, here James, is feeling naughty and decides to do this to the operation system because he does not want his boss to see these pictures…”, it makes the audience attentive and brings a human dimension to the speech.

The Laugh-a-minute:: Just employ humor over and over again
  Everybody likes a jokes or two, so long as the joke is politically correct and does not involve a pair of donkeys and a beautiful princess. ( you are supposed to laugh at this point…)
  When employing this technique, the speaker uses humor, his improvisation and some jokes he heard in the past and blends it in his speech. Puns could be used as well if it is tasteful in nature.
  “He is arguably the best public speaker in this club. To say that he is the best public speaker would lead to a heated argument. “ or
  “Urggh !!! It was so bad, a bed-ridden quadriplegic in an intensive care unit could play the piano better than her daughter did !!! “

The fountain of knowledge:: Tap into books for knowledge and wisdom
  The problem with “knowledgeable” people is that they seldom possess the right skills to package the information to make it interesting, this technique is therefore risky at best. The speaker has to read widely and possess special skills, here are a series of leads which could allow a speaker to dazzle the audience with his showmanship and knowledge.

==== Quotes


A speaker always has a arsenal of 20 or so quotes which can be used for most occasions.

[quote, Ancient philosophy]
The speaker should focus on general themes which could only be covered by such a subject matter like Happiness, Decisiveness, Friendship, Wisdom. The occasional reference to a philosopher like Socrates could reinforce the point made in a speech. It would also be useful to understand that people have begun thinking about the same questions that we have

[quote, Business / Management]
For working audiences the occasional reference to Peter Drucker or Bill Gates may be used to show how well informed you are. More importantly, many motivational speakers tend to give jaded audiences the impression that they lack solid content in their presentations.

[quote, Great Literature]
Another general field which demonstrates how people behave in interesting circumstances. Ralph Waldo Emerson is probably the most misquoted writer in the Toastmasters movement. The poet/philosopher has written widely in topics like “Self-Reliance”, “Love” . The ever popular William Shakespeare has written works which paints a pictures of the human condition in various circumstance in many of his Great works.

[quote, History]
The ability to remember a date will be viewed favorably by a discerning audience. More importantly the ability to relate the various events which happened in the past with some degree of accuracy would mean that the audience would be informed of history, thus, ensuring that “history does not repeat itself”.
  