
=== Happiness Week 3

==== Empathy, end of week 2

==== Honing Your Own Empathy

==== Wait, But What Is Compassion?

===== why are we compassionate?

===== Definitions

Kindness:: is a general, everyday term describing behaviors that involve being friendly, generous, or considerate. Pro-social is the term favored by scientists to refer to kind, helpful behaviors or states, but it is also quite broad.

Compassion:: Literally means “to suffer together.” Among emotion researchers, it is defined as the feeling that arises when you witness another’s suffering and feel motivated to help relieve that suffering.
Compassion is not the same as empathy or altruism, though the concepts are related. While empathy refers more generally to our ability to sense the emotions--and/or take the perspective--of another person, compassion is when those feelings and thoughts include the desire to help. While altruism is often prompted by compassion, one can feel compassion without acting on it, and altruism isn’t always motivated by compassion.

Altruism:: Altruism is when we act to promote someone else’s welfare, even at a risk or cost to ourselves. Many debate whether and why true (or "pure") altruism actually exists. Evolutionary scientists speculate that altruism has deep roots in human nature because helping and cooperation promote the survival of our species. Indeed, Darwin himself argued that altruism, which he called “sympathy” or “benevolence,” is “an essential part of the social instincts.” Some evolutionary biologists argue that organisms may sometimes put themselves at risk in order to help another because they expect that the other organism will return the favor down the line, a concept known as reciprocal altruism.

Empathy:: As Emiliana explained last week, the term “empathy” is used to describe a wide range of experiences. Emotion researchers generally define empathy as the ability to sense other people’s emotions (affective empathy), coupled with the ability to imagine what someone else might be thinking or feeling (cognitive empathy).

Sympathy:: (partecipazione) Sympathy, which means "to feel together," is sometimes used synonymously with compassion. However, while sympathy does refer to feelings of sorrow or sadness about another person's suffering, it does not typically involve the urge or motivation to help, or do anything about the situation. In other words, a person may feel sympathetic towards another person's difficulties, but not feel inclined to help. 

Pity:: (Pena) Feeling sorry for the suffering or misfortune of someone else. Pity is similar to compassion, but it suggests a power imbalance, whereby the observer occupies a place of superiority and looks down upon the person who is suffering.

===== Why Does Compassion Matter?

===== Measuring compassion in the body
 
==== How Kindness Boosts Happiness

===== Happiness for a Lifetime

===== Evolved to Be Kind


===== It Feels Good to be Kind


===== Altruism Quiz - 5 Ways Giving Is Good for You


<<<

==== Random Acts of Kindness

This practice involves performing five acts of kindness in one day. Is there a day in the next week when you have free time and might be able to do this practice? If so, write it in the space below.

.Giorno in cui ipotizzi la pratica
____
.
____

 
.Idee per atti di gentilezza, cose che hai ricevuto e che ti hanno fatto piacere
____
.

.

.

.
____


.Atti di gentilezza fatti da te in passato.
____
.

.

.

.
____


 
.5 Atti da fare nel *Random Acts of Kindness day*
____
1.	

2.	

3.	

4. 

5.	
____

.Metti in calendario il tuo *Random Acts of Kindness day* e prepara eventuale materiale/supporto per quel giorno.

Anche se puoi pianificarli, permettiti di agire spontaneamente se le opportunità avanzano. 

.Non dimenticarti di scrivere come ti hanno fatto sentire!

Ricorda! Scrivi!

NOTE: One day this week, perform five acts of kindness—all five in one day. It doesn’t matter if the acts are big or small, but it is more effective if you perform a variety of acts.
The acts do not need to be for the same person—the person doesn’t even have to be aware of them. Examples include feeding a stranger's parking meter, donating blood, helping a friend with a chore, or providing a meal to a person in need.
After each act, write down what you did in at least one or two sentences; for more of a happiness boost, also write down how it made you feel.

Kindness boosts happiness as it encourages people to bring happiness to others. But even knowing this, it can be hard to get started and stick with a happiness practice like Random Acts of Kindness.


==== SKEPTICAL VIEWS ON COMPASSION AND KINDNESS

