
==== Forgiving Practice

The names of people who have hurt you deeply enough to warrant the effort to forgive. If people come to mind, write down their initials in the spaces below.  

. -
. -
. -
. -
. -

for each person you listed, rate on a scale of 1-10 how much pain you still have regarding how that person treated you, with 1 involving the least pain (but still significant enough to justify the time to forgive) and 10 involving the most pain.

[options="header"]
|==============
| |  1  least pain | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 most - pain
| Person 1 |  | | | | | | | | | 
| Person 2 |  | | | | | | | | | 
| Person 3 |  | | | | | | | | | 
| Person 4 |  | | | | | | | | | 
| Person 5 |  | | | | | | | | | 
|==============

.TIME REQUIRED

Each person will forgive at his or her own pace. We suggest that you move through the steps below based on what works for you. 

.HOW TO DO IT

1. Make a list of people who have hurt you deeply enough to warrant the effort to forgive. You can do this by asking yourself on a 1-to-10 scale, How much pain do I have regarding the way this person treated me?with 1 involving the least pain (but still significant enough to justify the time to forgive) and 10 involving the most pain. Then, order the people on this list from least painful to most painful. Start with the person lowest on this hierarchy (least painful).
2. Consider one offense by the first person on your list. Ask yourself: How has this person’s offense negatively impacted by life? Reflect on the psychological and physical harm it may have caused. Consider how your views of humanity and trust of others may have changed as a result of this offense. Recognize that what happened was not okay, and allow yourself to feel any negative emotions that come up.
3. When you’re ready, make a decision to forgive. Deciding to forgive involves coming to terms with what you will be doing as you forgive—extending an act of mercy toward the person who has hurt you. When we offer this mercy, we deliberately try to reduce resentment (persistent ill will) toward this person and, instead, offer him or her kindness, respect, generosity, or even love.  
It is important to emphasize that forgiveness does not involve excusing the person’s actions, forgetting what happened, or tossing justice aside. Justice and forgiveness can be practiced together. 
Another important caveat: To forgive is not the same as to reconcile. Reconciliation is a negotiation strategy in which two or more people come together again in mutual trust. You may not choose to reconcile with the person you are forgiving.
4. Start with cognitive exercises. Ask yourself these questions about the person who has hurt you: What was life like for this person while growing up? What wounds did he or she suffer from others that could have made him or her more likely to hurt you? What kinds of extra pressures or stresses were in this person’s life at the time he or she offended you? These questions are not meant to excuse or condone, but rather to better understand the other person’s areas of pain, those areas that make him or her vulnerable and human. Understanding why people commit destructive acts can also help us find more effective ways of preventing further destructive acts from occurring in the future. 
5. Be aware of any little movement of your heart through which you begin to feel even slight compassion for the person who offended you. This person may have been confused, mistaken, and misguided. He or she may deeply regret his or her actions. As you think about this person, notice if you start to feel softer emotions toward him or her.
6. Try to consciously bear the pain that he or she caused you so that you do not end up throwing that pain back onto the one who offended you, or even toward unsuspecting others, such as loved ones who were not the ones who wounded you in the first place. When we are emotionally wounded, we tend to displace our pain onto others. Please be aware of this so that you are not perpetuating a legacy of anger and injuries.
7. Think of a gift of some kind that you can offer to the person you are trying to forgive. Forgiveness is an act of mercy—you are extending mercy toward someone who may not have been merciful toward you. This could be through a smile, a returned phone call, or a good word about him or her to others. Always consider your own safety first when extending kindness and goodwill towards this person. If interacting with this person could put you in danger, find another way to express your feelings, such as by writing in a journal or engaging in a practice such as compassion meditation. 
8. Finally, try to find meaning and purpose in what you have experienced. For example, as people suffer from the injustices of others, they often realize that they themselves become more sensitive to others’ pain. This, in turn, can give them a sense of purpose toward helping those who are hurting. It may also motivate them to work toward preventing future injustices of a similar kind.
9. Once you complete the forgiveness process with one person on your list, select the next person in line and move up that list until you are forgiving the person who hurt you the most.
