
== Risorse interne

160125
76G	    Mao/
141G	Foto/
272G	dlna_dir/ 
279G	Books/


== Risorse Esterne

=== Elenco Letture da affrontare

==== Comunicazione

--------------------------

Nudge - la spinta gentile. Thalesman

Enrico rolla - il problema c'è l'hai tu non io

Zizzarelli - Impara a dire no

Le sette brevi lezioni di fisica

Robert Cialdini - le armi della persuasione

Introduzione alla PNL - nlp italy

Metafore per bambini

Introduzione alla pnl

Robertson ted

--------------------------

==== Medicina

* http://www.cochranelibrary.com/

==== Negoziazione

Gavin Kennedy, padre degli 8 Steps Approach

* Keith Spicer
 ** Winging It (1981)
 ** Think on Your Feet (1986)


==== Organizzarsi

Reinventing Organizations - Frederic Laloux

==== Narrativa

blablabla

--------------------------

-   Il Condominio di James G. Ballard
-   È difficile essere un Dio di Strugatski Boris e Arkadi

--------------------------

blablabla

==== Fumetti

* 100 bullet
* terru moore echo
* Yann, Berthet - Pin-up
* Jack Of Fables 22-35
* Il Punitore
* The Literals 1-3
* Le Prove Di Shazam
* Voyager 06 - Alfa e Omega
* battlefields
* moebious


=== FIlms

* Commedie
  ** Sideways
  ** Impiegati male
  ** Notorius Big
  ** Wall Street
  ** Il Verdetto
* Interessanti
  ** Patton
  ** High and low toshiro mifune



=== Software da conoscere

blablabla

--------------------------

-   [Sinfig studio](http://www.synfig.org): per animazioni 2D.
-   [BlackMagic Fusion](https://www.blackmagicdesign.com/products/fusion): aminazioni 2D e 3D professionali.

--------------------------


=== Wii

--------
    Alone In The Dark 
    Back To The Future: The Game 
    Battalion Wars 2 
    Call Of Duty World At War 
    Dead Space Extraction 
    Fantastic Four Rise of the Silver Surfer 
    Far Cry: Vengeance 
    FIFA 12 
    Ghost Squad 
    GoldenEye 007 
    Marvel Super Hero Squad 
    Metroid Prime Trilogy 
    NBA Jam 
    Pictionary 
--------

=== PS2

http://www.moddingstudio.com/showthread.php?2533-SoftMod-tramite-Free-MC-Boot-(non-compatibile-slim-90004)


=== Siti


* Acquisti
    ** http://www.gearbest.com
	** http://www.grossoshop.net/
    ** http://www.tinydeal.com
    ** http://www.everbuying.com
    ** http://http://www.grossoshop.net/
    ** Specifici cellulari
        *** http://comebuy.com
    
* Android
    Acr call     
* Grafica
    ** Gallerie fotografiche http://www.makeuseof.com/tag/top-linux-photo-software-managing-editing-snaps/


   

=== Cose da Comprare

    * Telefoni
        ** Doogee F2 Ibiza

Sugg Roffi 
* Blackview
* 130
* Cubot

		
=== Corsi da fare

* https://www.udemy.com/financial-analysis-a-recipe-for-success/
* https://www.futurelearn.com/courses/informed-health-consumer
* https://www.futurelearn.com/courses/the-science-of-nutrition
* https://www.udemy.com/chess-tactics-101/
* https://www.coursera.org/learn/negotiationf


== Tecnologie Interessanti

- Backbeat PLantronics


==Add ONS

=== Cambiamento

Servono 10000 ore per sostituire un'abitudine

Change - Paul Watzlawick. Su come affrontare il cambiamento.

=== Esercizi


Tabata 3X

. Burpees
. TRX
. Roll & Jump
. Swing
. Handstand
. Frog Squat
. Gatto Morto
. Kick Sit

.Zuu - Solihull Drill
3X:
- 8 Russian
- 10 Frog


=== Appunti Gratitudine

Gratitude Journal: The Why and the How
Why You Should Try It

It’s easy to take the good things and
people in our lives for granted, but research suggests that consciously
giving thanks for them can have profound effects on our well-being and
relationships. This exercise helps you develop a greater appreciation
for the good in your life. In fact, people who routinely express
gratitude enjoy better health and greater happiness.

Time Required

15 minutes per day, at least once per
week for at least two weeks. Studies suggest that writing in a gratitude
journal three times per week might actually have a greater impact on
our happiness than journaling every day.

How to Do It

There’s no wrong way to keep a gratitude
journal, but here are some general instructions as you get
started. Write down up to five things for which you feel grateful. The
physical record is important—don’t just do this exercise in your head.
The things you list can be relatively small in importance (“The tasty
sandwich I had for lunch today”) or relatively large (“My sister gave
birth to a healthy baby boy”). The goal of the exercise is to remember a
good event, experience, person, or thing in your life—then enjoy the
good emotions that come with it.

As you write, here are nine important tips:

Be as specific as
possible—specificity is key to fostering gratitude. “I’m grateful that
my co-workers brought me soup when I was sick on Tuesday” will be more
effective than “I’m grateful for my co-workers.”Go for depth over
breadth. Elaborating in detail about a particular person or thing for
which you’re grateful carries more benefits than a superficial list of
many things.Get personal.
Focusing on people to whom you are grateful has more of an impact than
focusing on things for which you are grateful.Try subtraction, not
just addition. Consider what your life would be like without certain
people or things, rather than just tallying up all the good stuff. Be
grateful for the negative outcomes you avoided, escaped, prevented, or
turned into something positive—try not to take that good fortune for
granted.See good things as
“gifts.” Thinking of the good things in your life as gifts guards
against taking them for granted. Try to relish and savor the gifts
you’ve received.Savor surprises. Try to record events that were unexpected or surprising, as these tend to elicit stronger levels of gratitude.Revise if you repeat. Writing about some of the same people and things is OK, but zero in on a different aspect in detail.Write regularly.
Whether you write every other day or once a week, commit to a regular
time to journal, then honor that commitment. But…Don’t overdo it.
Evidence suggests writing occasionally (1-3 times per week) is more
beneficial than daily journaling. That might be because we adapt to
positive events and can soon become numb to them—that’s why it helps to
savor surprises.


====Behaviour of grateful people

. Once in a while, they think about death and loss
. They take the time to smell the roses
. They take the good things as gifts, not birthrights
. They’re grateful to people, not just things
. They mention the pancakes


