:doctype: article
:encoding: utf-8
:toc:
:toc-placement: preambe
:toclevels: 4


= Sacmi


With a corporate capital of just 4,500 Italian
Lire (2 euros in today’s money) and a
nine-strong staff of mechanics and blacksmiths,
in 1919 the Società Anonima Cooperativa
Meccanici Imola began an odyssey
that would, thanks to growing market
internationalisation and a steady process
of innovation and product differentiation,
transform it into one of the world’s leading
plant engineering firms.
Unremitting determination on the part of
its members allowed SACMI to get through
the difficult 1930s - a period marred by
dictatorship and unfavourable economic
circumstances - and successfully complete
their first machine, which was designed to
clean oranges. After the Second World War,
SACMI contributed to Italy’s reconstruction
by developing the early technology for the
ceramic-making firms of the Sassuolo industrial
district and the wider region of Emilia-
Romagna. It also started building machines
for the production of metal crown caps, a
foretaste of what would later become the
Group’s multi-business strategy.
The 1960s/1970s were characterised by a
successful, export-driven international expansion
policy, takeovers of other companies
and business units and the establishment
of subsidiaries. Steadily, then, the
Cooperative began to take on the appearance
of a large multinational. By the year
2000 it had become a key player not only
in ceramic plant engineering but also in the
beverage and packaging, food processing
and plastic industries; today, the number of
members and *employees* has surged from
the original nine to *4,180*, the Group generates
*revenues* of some *1,354 millions euro*
and has a *net worth of 621 million euro*.

At present the Group has production plants,
distribution companies and service companies
in 30 countries and the parent company
in Imola (Bologna, Italy) now controls
more than 75 firms while the SACMI brand
is registered in over 100 countries worldwide.
This far-reaching global presence explains
why 87% of Group sales come from
exports.

Investments in R&D in 2015 were in line with
the previous years with the Group setting
aside over 60 million Euros. This highlights
the Group’s clear commitment to further development
and strengthening of the knowhow
that has made SACMI a leading international
provider of industrial technology.
The Center (R&D) occupies
11,700 square meters of floor space and
employs over 200 researchers and technicians,
all involved in developing cuttingedge
expertise in the ceramic, packaging
and process control system fields and making
it available to the entire Group.

total number of registered inventions
in the Group’s history to approximately
500 and the total number of registered
patents to 3,500.



Year, Turnover (M€), Equity(M€), Ebitda, Ebit, Investiments, Employees:: 
	* 2011 1303, 572, 161, 124, 49, 3963
	* 2012 1243, 585, 145, 109, 40, 3919
	* 2013 1227, 593, 155, 120, 47, 4175
	* 2014 1196, 601, 146, 111, 38, 3917
	* 2015 1354, 621, 156, 120, 65, 4180



== Ceramics 

Year, Turnover (M€), Employees:: 
	* 2013 764, 2243
	* 2014 798, 2303
	* 2015 849, 2312


=== Tiles

* Scami Imola Sc
* Nuova Sima
** Nuova Fima
** Sima
** Kemac
* Keratech
* Surface inspection
* Kemac
* Intesa
* Cuccolini
* Sacmi Molds & Dies
* CMC
* Eurofilter

=== Whiteware

* Sacmi Imola Sc
* Riedhammer
* Sama
* Gaiotto
* Team
* LAEIS
* Alpha ceramics

=== Special pressing

* Sacmi Imola Sc
* Riedhammer
* LAEIS
* Alpha ceramics
* Gaiotto

=== Heavy Clay

* Sacmi Imola Sc
* Gaiotto
* Cosmec

== Packaging 

Year, Turnover (M€), Employees:: 
	* 2013 305, 1026
	* 2014 308, 1087
	* 2015 347, 1069

=== Closures & containers
* Sacmi Imola SC

=== Beverage
* Sacmi Imola SC
* Sacmi Filling
* Sacmi Labelling

=== Packaging
* Sacmi Packaging
* Benco Pack
* Sima

== Food

Year, Turnover (M€), Employees::
	* 2013 97, 330
	* 2014 102, 338
	* 2015 118, 337



=== CMH Holding: 

* CM OPM
* CM FIMA


== Automation & Service

Year, Turnover (M€), Employees::
	* 2013 18, 89
	* 2014 18, 95
	* 2015 19, 92

=== Inspection Systems
* Sacmi

=== Service

Year, Turnover (M€), Employees::
	* 2013 62, 274
	* 2014 66, 264
	* 2015 77, 370

Aziende:

* Sacmi Service
* ABizCo
* Italian
* Protesa
* Iprel Progetti



== Altri appunti

=== Domande

Continua+, Forno Eko

== Lista Aziende

=== Alpha Ceramics

ALPHA CERAMICS in Aachen, an optimally equipped technical center, 
offers a broad variety of services for the ceramic industry as well as 
for adjacent sectors, ranging from trials and process development up to 
toll manufacturing of certain products. Furthermore, proprietery 
products are being developed and directly marketed, especially different
 types of kiln furnitures. Also small scale manufacturing of customer 
products is possible.

Being a subsidiary of  http://www.laeis.eu/[LAEIS GmbH]
 in Wecker, Luxembourg, ALPHA CERAMICS provides testing capacity as well
 as process and machinery development facilities for LAEIS customers.  

ALPHA CERAMICS is also member of http://www.sacmi-team.com/[TEAM by Sacmi], an alliance of SACMI group companies supplying the technical ceramics industry.


=== CMC

Costruzioni Meccaniche per Ceramiche – Automazioni Industriali

Macchine::

	- Raccoglitore Pressa a Rulli
	- Carrelli
	- Asservimento / Scarico PHP
	

=== COSMEC 

Partner for automation of the heavy clay production processes and provides some of the most advanced and high-performance solutions of the market in any production area: from load-bearing blocks to holed filler bricks, from tiles to continuous façade elements, from flooring elements to special applications.

=== Eurofilter

Impianti di purificazione per polveri

=== Gaiotto

Gaiotto is now regarded as the world’s leading producer of highly-automatic glazing and painting plants.   

Forty years of research and experience have led to the development of 
advanced products that comply with the very highest standards of quality
 and reliability.   

Gaiotto operates in the fields of ceramics, plastics and general 
industry. Its mission is to provide turnkey plants that use a 
combination of both its own robots and those made by other producers, 
with tooling, engineering and customer-specific personalization being 
carried out by Gaiotto.   

Constantly on the industry’s cutting edge, Gaiotto has succeeded in 
becoming a key system integrator by steadly raising the level of applied
 know-how within the various fields in which it operates.   

Thanks to its in-depth knowledge of robotized systems at both software 
and hardware level, its evolved design skills and qualified customer 
service, Gaiotto has constantly managed to combine technical knowledge 
with marked innovation.
                                

=== IN.TE.SA. S.p.A. 

Produces glazing lines and digital printing machines footnote[è una società del Gruppo Sacmi specializzata nella produzione e fornitura di tecnologie per la smaltatura e la decorazione di piastrelle]

Divisions:

* Digital Technology
	** Single-pass digital printers
	** Multi-pass digital printers (plotter)
	** Color Management System
* Glazing and silk-screen printing
* Sieving and Deferrization
** Sieving
  *** Press feeding
  *** Powders sieving
  *** Sieves for slips
  *** Sieves for glazes
  *** Trolley units
** Deferrization
  *** Powders deferrization
  *** Fluids deferrization
** Dissolving
  *** Dissolvers for powders


=== LAEIS

LAEIS offers presses and machinery for various applications.
  
=== Mectiles

Purchases, collects, overhauls and sells second-hand ceramic manufacturing machinery.

=== Riedhammer

2015:: Highlights
	* has strengthened its market share in the special ceramic kiln sector and reinforced its position in more traditional fields such as sanitaryware, tableware, refractory and graphite anodes.
	* Further development of the metal powder
	* Moreover, market shares vis-à-vis kilns used to fire the ceramic components found in electric car batteries have increased significantly: this segment is expected to generate considerable sales in the short term.
	
=== SAMA 

2016 -- 25th anniversary. 

* Fully automatic production of cups with handles (news 2016).
* Solutions for Technical Ceramics:
	- Body and glaze preparation
		... Sacmi Imola
		... Sama Maschinenbau
	- Shaping
		... Laeis
		... Sama Maschinenbau
	- Additional Operations
		... Sama Maschinenbau

		
=== Sacmi Forni

1985::  The Sacmi Group acquires 70% of Heimsoth Forni, the Italian subsidiary of Heimsoth Hildesheim GmbH, manufacturer of kilns for the ceramic industry, with special attention to the tiles sector: this was the birth of Sacmi Forni.

1994:: The Sacmi Group becomes sole proprietor of Sacmi Forni. A new plant is built at Salvaterra di Casalgrande, to which all operations are transferred in 1995.

1997:: Sacmi Forni acquires the production line of business of Eurotech, a kilns manufacturer that is already controlled by the Sacmi Group. With this acquisition/merger Sacmi Forni enters alternative sectors to ceramic tiles for the first time (sanitary ware, tableware, extruded products and frit kilns).

1998:: Sacmi acquires a stake in Keratech, a leading manufacturer of refractory materials (rollers) for firing of ceramic tiles. The same year Sacmi Forni wins the Compasso d’Oro design award with the Fmp single-layer roller kiln for tiles. Sacmi makes history by becoming the first company in the ceramics sector to dedicate special attention to the ergonomic and environmental factors that will characterise all of the machines produced thereafter.

2000:: The parent company develops a new "Whiteware" business unit focusing on the sanitary ware and tableware production processes.

2001:: Sacmi Forni launches a new division, denominated Sacmi Automation, to develop machinery and integrated solutions for sorting, packaging, and handling of ceramic tiles.

2002:: Sacmi Forni presents a new tunnel kiln for sanitary ware, model XLNt, which is designed to offer the optimal combination of plant energy efficiency and process quality while simultaneously facilitating the interface between the plant and human operators and minimising environmental impact factors.

2003:: Sacmi Forni enters the bricks sector with the Heavy Clay division.

2005:: Sacmi Forni celebrates 20 years of operations

2007-2010:: Kemac  , a Sacmi Group company, joins the Sacmi Forni family, distributing its resources in the company's two fields of activity: Ceramics & Tiles / Automation. In 2010, within a Sacmi Group's companies reorganization process, is established a New Automation Centre, in which Kemac first and, the following year, Automation converge. The company currently has 2 divisions: Thermal and Heavy Clay. 

2011:: The same reorganization process involves Ceramic's District logistics activities, so that arises the "Integrated Logistics Centre" under the aegis of Italiansped (logistics company of Sacmi Group), in which Sacmi Forni goods' management and shipping merge. 
		
=== Team by Sacmi

TEAM by SACMI integrates all the innovative skills and technologies of Sacmi Imola, Alpha Ceramics, Laeis, Riedhammer and Sama, leaders in the design and construction of ceramic production plants.
                
           
           
=== Carpmec

ciccia

=== TLR Italia

Ciccia

=== Cosmec

Ciccia
                

Sotto la dirrezione generale esistono:

- 4 direzioni generali di Business Unit:
* Ceramica::
** Piastrelle
** Sanitari
** Stoviglie
** Laterizi
** Estrusi
** Referattari
** Polveri metalliche sinterizzate
** Imbutitura metalli
* Packaging
** Tappi
** contenitori (closures)
** Imbottigliamento
** Etichettaggio
** Fardellamento
* Food
** Cacao
** Cioccolato
** Confezionamento primario e secondario di alimenti
* Service & Automation
** Spedizioni e logistica
** Servizi amministrativi, legali e fiscali
** Srvizi informatici
** Vendita ed installazione
** Servizio metrologia e controllo qualità
** Sistemi ispettivi di processo

Con il crescere dell'esternalizzazione e la varietà delle produzioni hanno fatto sì che si creasse un ente dedicato all'*industrializzazione delle macchine*:

* Controllo qualità
* Tempi e metodi d'officina
* Preventivi di costi
* Gestione archivio dei costi visibili da contabilità e acquisti.
  
=== Overview

Presidente:: Paolo Mongardi
Direttore Generale:: Pietro cassani

Bilancio 2015::
	Turnover: 1.354 mld €
	


=== Buying Center 

* Sacmi SC
   ** Rocchi
    ***
* Sacmi Filling
   ** Pasquina Rinaldi (commerciali)
   ** Mauro Raschi (pezzi a disegno)
* Sacmi Packaging 
   ** Liverani Adolfo
* Sacmi Verona
   ** Flaviano.Raschietti@sacmi.it *responsabile*
   ** Pascuale petronio operativo
    

include::beverage.adoc[]
include::filling.adoc[]
include::imola.adoc[]
include::packaging.adoc[]]
include::pet_projecta.adoc[]]
include::verona.adoc[]

== Macchine

Sacmi::
    * CHS Closure Handling System (plastic and aluminium caps)
    * LHS Label Vision System
    * MHS Metal Vision System

== Internal Shortcuts

BW::  analisi Gruppo GD Agreement